import KeyMirror from '../utils/keymirror';

const AccountCloseConstants = KeyMirror('ACCOUNT_CLOSE', [
    'SHOW_PRODUCT_PICKER',
    'CLOSE_PRODUCT_PICKER',
    'PICK_PRODUCT',
    'CLEAR_PRODUCT',
    'SEARCH_PRODUCT',
    'CLEAR_SEARCH_PRODUCT',

    'SHOW_COMMISSION_PRODUCT_PICKER',
    'CLOSE_COMMISSION_PRODUCT_PICKER',
    'PICK_COMMISSION_PRODUCT',
    'CLEAR_COMMISSION_PRODUCT',
    'SEARCH_COMMISSION_PRODUCT',
    'CLEAR_SEARCH_COMMISSION_PRODUCT',

    'FETCH_COMMISSION_REQUEST',
    'FETCH_COMMISSION_SUCCESS',
    'FETCH_COMMISSION_FAILURE',

    'SET_IS_LOADED',

    'CLOSE_ACCOUNT_SUCCESS',
    'SET_INITIAL_VALUES',
]);

export const REST_TRANSFER_OPTIONS = { TOPRODUCT: 'TOPRODUCT', TOBANK: 'TOBANK' };

export default AccountCloseConstants;
