export default {
    LOGIN: 'LOGIN',
    LOGOUT: 'LOGOUT',
    REGISTRATION: 'REGISTRATION',
    PAGE_LOGIN: 'PAGE_LOGIN',
    MAIN_PAGE: 'MAIN_PAGE',
    PAGE_REG: 'PAGE_REG',
    CHANGE_PAGE: 'CHANGE_PAGE',
}
